apiVersion: v1                    
kind: Namespace
metadata:
  name: book-import                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: book-import
  namespace: book-import
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - book-import
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: book-import-channel
  namespace: book-import
spec:
  type: Git
  pathname: 'https://github.com/tjungbauer/book-import.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master-no-pre-post
    apps.open-cluster-management.io/git-path: book-import
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: book-import
  name: book-import-subscription-1
  namespace: book-import
spec:
  channel: book-import/book-import-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: book-import-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: book-import
  name: book-import-placement-1
  namespace: book-import
spec:
  clusterSelector:
    matchLabels:
      'environment': 'local'
